apiVersion: batch/v1
kind: CronJob
metadata:
  name: page-scraper-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: page-scraper
              image: page-scraper
              imagePullPolicy: Never
              volumeMounts:
                - name: database
                  mountPath: /var/db
          restartPolicy: OnFailure
          volumes:
            - name: database
              persistentVolumeClaim:
                claimName: page-scraper-pvc
                readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: page-scraper-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 256Mi
