apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
data:
  config.py: |
    MIN_FLOOR = 3
    MAX_COST = 130000
    MIN_COST = 50000
    ROOMS = 3
    NTFY_URL = "https://ntfy.sh/tesy"
    SS_URL = "https://www.ss.com/lv/fTgTeF4QAzt4FD4eFFM=.html?map=17020&map2=17020&cat=14195&mode=3"
    SS_COOKIES_URL = "https://www.ss.com/lv/real-estate/flats/riga/all/fDgQeF4S.html"
    REGIONS_FILE = "/app/bad_regions.geojson"
