apiVersion: batch/v1
kind: CronJob
metadata:
  name: page-scraper
  namespace: default
  labels:
    app.kubernetes.io/name: page-scraper
spec:
  successfulJobsHistoryLimit: 3
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: page-scraper
              image: ghcr.io/0wlie22/page-scraper/page-scraper:latest
              imagePullPolicy: Always
              env:
                - name: DB_PATH
                  value: /var/db/db.json
              volumeMounts:
                - name: database
                  mountPath: /var/db
                - name: config-volume
                  mountPath: /app/src/config.py
                  subPath: config.py
                - name: regions-volume
                  mountPath: /app/bad_regions.geojson
                  subPath: bad_regions.geojson
          restartPolicy: OnFailure
          volumes:
            - name: database
              persistentVolumeClaim:
                claimName: page-scraper-pvc
                readOnly: false
            - name: config-volume
              configMap:
                name: python-app-config
            - name: regions-volume
              configMap:
                name: geo-config
