apiVersion: batch/v1
kind: CronJob
metadata:
  name: page-scraper
  namespace: flat-scraper
  labels:
    app.kubernetes.io/name: page-scraper
spec:
  successfulJobsHistoryLimit: 3
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: page-scraper
              image: ghcr.io/0wlie22/flat-scraper:latest
              imagePullPolicy: Always
              env:
                - name: PS_DB_PATH
                  value: /var/db/db.json
              volumeMounts:
                - name: database
                  mountPath: /var/db
          restartPolicy: OnFailure
          volumes:
            - name: database
              persistentVolumeClaim:
                claimName: page-scraper-pvc
                readOnly: false
