apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: page-scraper
  namespace: flat-scraper
  labels:
    app.kubernetes.io/name: page-scraper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
