name: Build Docker Image

on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Github Container Registry: Build and push Docker image"
        uses: pmorelli92/github-container-registry-build-push@2.1.0
        with:
          github-push-secret: ${GITHUB_TOKEN}
          docker-image-name: flat-scraper
